import type { Metadata } from 'next';
import { Oxanium } from 'next/font/google';
import './globals.css';
import { TRPCReactProvider } from '@/trpc/client';
import { Toaster } from '@/components/ui/sonner';

const oxanium = Oxanium({
  subsets: ['latin'],
  variable: '--font-oxanium',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={oxanium.variable}>
        <body className={`antialiased font-sans`}>
          {children}
          <Toaster />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
